/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum Status
{
  OK = 0,
  FAILED = 1,
  ERROR = 2,
  UNKNOWN = 3,
}
